#!/bin/env bash
#  description: very simple litle script to change walpaper and dwm coloscheme with xrdb patch
# dependencies: pywal, notify-send, colorthief, haishoku, colorz, feh.
#       author: Aldo Solis
#         date: 18/06/2024
#  last-update: 2025-06-21

WALL_DIR="$HOME/Wallpapers"

if [ ! -d $WALL_DIR ]; then
  notify-send "chwal" "Directory $WALL_DIR does not exist!" 
  exit 1
fi

WALLPAPER="$(ls $WALL_DIR | dmenu -p "Wallpaper")"
if [ -z $WALLPAPER ]; then 
  notify-send "chwal" "Error: No wallpaper specified" 
  exit 3
fi

# set slock bg image
ln -sf "$WALL_DIR/$WALLPAPER" "$WALL_DIR/current.wal"
rm $HOME/.cache/wal/schemes/_home_aldosolisr_Wallpapers_current_wal_**

BACKEND="$(printf "colorthief\nhaishoku\nwal\ncolorz" | dmenu -p "backend" )"
if [ -z $BACKEND ]; then 
  notify-send "chwal" "Error: No backend specified" 
  exit 3
fi

# set bg image and update dwm colorschemes
wal -q --backend $BACKEND -i $WALL_DIR/$WALLPAPER
xsetroot -name "fsignal:1" 
notify-send Done! 
